from __future__ import annotations

class F64Unit:
    def parse(self, s: str) -> F64Unit: ...

class F64Quantity:
    def __init__(self, value: float, units: F64Unit) -> None: ...

    @staticmethod
    def parse(expression: str) -> F64Quantity: ...

    @property
    def m(self) -> float: ...

    @property
    def magnitude(self) -> float: ...

    @property
    def u(self) -> F64Unit: ...

    @property
    def units(self) -> F64Unit: ...

    def to(self, units: str | F64Unit) -> F64Quantity: ...

    def ito(self, units: str | F64Unit) -> None: ...

    def m_as(self, units: str | F64Unit) -> float: ...
