[build-system]
requires = ["maturin>=1.8,<2.0"]
build-backend = "maturin"

[project]
name = "smoot"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
    "typing_extensions>=4.12.2",
]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
sdist-include = ["smoot/data/*"]

[dependency-groups]
dev = [
    "maturin>=1.8.3",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "ruff>=0.11.7",
]
